services:
  cong-esp-app:
    build: .
    container_name: cong-esp-app
    networks:
      - cong-esp-vila-guilherme-network
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/cong-esp
      QUARKUS_DATASOURCE_USERNAME: ${QUARKUS_DATASOURCE_USERNAME}
      QUARKUS_DATASOURCE_PASSWORD: ${QUARKUS_DATASOURCE_PASSWORD}
    depends_on:
      - db
    ports:
      - 8085:8080

  db:
    image: postgres:16
    container_name: postgres_db
    networks:
      - cong-esp-vila-guilherme-network
    environment:
      - POSTGRES_DB=cong-esp
      - POSTGRES_USER=${QUARKUS_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${QUARKUS_DATASOURCE_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432 

networks:
  cong-esp-vila-guilherme-network:
    external: true

volumes:
  db-data: