services:
  front:
    image: cong-esp-vila-guilherme-front
    container_name: cong-esp-vila-guilherme-front
    networks:
      - app-network
    ports:
      - 8080:80
    depends_on:
      - cong-esp-app
      - dotnet-api
  dotnet-api:
    image: cong-esp-vila-guilherme-api
    container_name: cong-esp-vila-guilherme-api
    environment:
      Email__Password: ${Email_Password}
      Email__Host: ${Email_Host}
      Email__Address: ${Email_Address}
      DynamoDB__secretKey: ${DynamoDB_secretKey}
      DynamoDB__accessKey: ${DynamoDB_accessKey}
      Auth__TokenSecret: ${Auth_TokenSecret}
      Auth__PasswordHashSecret: ${Auth_PasswordHashSecret}
      FrontAppHost: ${FrontAppHost}
      TsvUrl: ${TsvUrl}
    networks:
      - app-network
    ports:
      - 8081:8080

  cong-esp-app:
    build: .
    container_name: cong-esp-app
    networks:
      - app-network
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/cong-esp
      QUARKUS_DATASOURCE_USERNAME: ${QUARKUS_DATASOURCE_USERNAME}
      QUARKUS_DATASOURCE_PASSWORD: ${QUARKUS_DATASOURCE_PASSWORD}
    depends_on:
      - db
    ports:
      - 8085:8080

  db:
    image: postgres:16
    container_name: postgres_db
    networks:
      - app-network
    environment:
      - POSTGRES_DB=cong-esp
      - POSTGRES_USER=${QUARKUS_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${QUARKUS_DATASOURCE_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432 

networks:
  app-network:
    driver: bridge

volumes:
  db-data: