### Post a new record
POST http://localhost:8086/api/territory/assignment/record

{
    "territoryNumber" :20 ,
    "assignedTo" : "Tiago",
    "assignedDate" : "2025-06-20"
}

### Get full Sheet
GET http://localhost:8086/api/territory/assignment

### generate assignment Schedule
GET http://localhost:8086/api/meetings/assignment

### create meeting assingment type
POST http://localhost:8086/api/meetings/assignment/type

{
    "type": "ConducAtal"
}

### get meeting assingment type
GET http://localhost:8086/api/meetings/assignment/type

### post csv file content as string
POST http://localhost:8086/api/meetings/assignment/brother

{
    "name" : "teste brother"
}

### post csv file content as string
POST http://localhost:8086/api/meetings/assignment/brother/csv
Content-Type: text/plain

< C:\\Users\\tiago\\dev-projects\\python\\VilaGuilherme-Varones2.csv

### get brothers
GET  http://localhost:8086/api/meetings/assignment/brother


### add template colum
PUT http://localhost:8086/api/meetings/assignment/template
Content-Type: application/json

[
    {
        "label" : "Acomodador",
        "typeId": "9cca0aea-df1a-4a3a-8f13-105ce116c31e"
    },
    {
        "label" : "Acomodador",
        "typeId": "9cca0aea-df1a-4a3a-8f13-105ce116c31e"
    },
    {
        "label" : "Audio",
        "typeId":  "311ff0c4-e329-4b88-a1d6-93897904eeaa"
    },
    {
        "label" : "Video",
        "typeId":  "311ff0c4-e329-4b88-a1d6-93897904eeaa"
    },
    {
        "label" : "Microfono",
        "typeId":  "dac55759-62a4-4c1d-ab83-e988ab5237cd"
    },
    {
        "label" : "Microfono",
        "typeId":  "dac55759-62a4-4c1d-ab83-e988ab5237cd"
    }
]


### get weekend meeting schedule
GET http://localhost:8086/api/meetings/weekends


### assing watchtower study conductor
POST http://localhost:8086/api/meetings/weekends/watchtower-study-conductor

{
    "id": "e8eddfd7-28b7-44ca-87fd-f9243bcccfc7",
    "name": "Derik Leite",
    "assignments": []
  }

### update a public talk
POST http://localhost:8086/api/meetings/weekends/public-talk

{"date":"2025-07-27","speaker":"Pedro Farfan","publicTalkTheme":"¿En las promesas de quién confía usted?","outlineNumber":61,"isLocal":true,"congregation":""}


### update meeting assingnments
PUT http://localhost:8086/api/meetings/weekends/assignments

{
    "date": "2025-07-06",
    "president": "",
    "speaker": "Vanderlei Figueroa",
    "speakerCongregation": "Esp. Santo André",
    "publicTalkTheme": "Por qué es provechoso que los cristianos se mantengan separados del mundo",
    "outlineNumber": 119,
    "watchtowerStudyConductor": "Derik Leite",
    "watchtowerStudyReader": ""
  },

### get allowed brothers to weekend assignments
GET http://localhost:8086/api/meetings/weekends/brothers