### Post a new record
POST http://localhost:8080/api/territory/assignment/record

{
    "territoryNumber" :20 ,
    "assignedTo" : "Tiago",
    "assignedDate" : "2025-06-20"
}

### Get full Sheet
GET http://localhost:8080/api/territory/assignment