### Post a new record
POST http://localhost:8085/api/territory/assignment/record

{
    "territoryNumber" : 1,
    "assignedTo" : "Tiago",
    "assignedDate" : "2025-06-20",
    "completedDate": "2025-06-21"
}

### update completedDate
PATCH  http://localhost:8085/api/territory/assignment/record

{
    "recordId" : "f2a86355-0d2f-46c9-b912-7236047d678e",
    "completedDate": "2025-06-21"
}

### Get full Sheet
GET http://localhost:8085/api/territory/assignment

### generate assignment Schedule
GET http://localhost:8085/api/meetings/assignment

### update group list
PATCH http://localhost:8085/api/congregation/groups

[
    {
        "groupNumber" : 1,
        "groupOverseer" : "Antonio"
    },
    {
        "groupNumber" : 2,
        "groupOverseer" : "Jorge"
    },
    {
        "groupNumber" : 3,
        "groupOverseer" : "Joel Amador"
    },
    {
        "groupNumber" : 4,
        "groupOverseer" : "David"
    },
    {
        "groupNumber" : 5,
        "groupOverseer" : "Derik"
    }
]

### list all groups
GET http://localhost:8085/api/congregation/groups

### get cleaning list
GET http://localhost:8085/api/meetings/cleaning